package gui.frames;


import com.opencsv.CSVReader;
import javax.swing.JOptionPane;
import java.io.FileReader;
import java.io.IOException;


public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
        setLoginImage();
        this.setSize(950, 580);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelWhite = new javax.swing.JPanel();
        jPanelLogin = new javax.swing.JPanel();
        jTextFieldUsername = new javax.swing.JTextField();
        jLabelUsername = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jButtonLogin = new javax.swing.JButton();
        jLabelMotorph = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jLabelLoginCoverPhoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(72, 27));
        getContentPane().setLayout(null);

        jPanelWhite.setBackground(new java.awt.Color(255, 255, 255));
        jPanelWhite.setLayout(null);

        jPanelLogin.setBackground(new java.awt.Color(0, 51, 102));
        jPanelLogin.setLayout(null);

        jTextFieldUsername.setBackground(new java.awt.Color(214, 228, 243));
        jTextFieldUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsernameActionPerformed(evt);
            }
        });
        jPanelLogin.add(jTextFieldUsername);
        jTextFieldUsername.setBounds(130, 230, 290, 30);

        jLabelUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelUsername.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsername.setText("Username:");
        jPanelLogin.add(jLabelUsername);
        jLabelUsername.setBounds(130, 210, 160, 20);

        jLabelPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPassword.setText("Password:");
        jPanelLogin.add(jLabelPassword);
        jLabelPassword.setBounds(130, 280, 150, 20);

        jButtonLogin.setBackground(new java.awt.Color(242, 242, 242));
        jButtonLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(0, 51, 102));
        jButtonLogin.setText("Log In");
        jButtonLogin.setToolTipText("");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        jPanelLogin.add(jButtonLogin);
        jButtonLogin.setBounds(200, 390, 160, 40);

        jLabelMotorph.setFont(new java.awt.Font("Segoe UI", 0, 43)); // NOI18N
        jLabelMotorph.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMotorph.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMotorph.setText("Login");
        jPanelLogin.add(jLabelMotorph);
        jLabelMotorph.setBounds(120, 90, 120, 90);

        jPassword.setBackground(new java.awt.Color(214, 228, 243));
        jPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });
        jPanelLogin.add(jPassword);
        jPassword.setBounds(130, 300, 290, 30);

        jPanelWhite.add(jPanelLogin);
        jPanelLogin.setBounds(390, 0, 550, 550);
        jPanelWhite.add(jLabelLoginCoverPhoto);
        jLabelLoginCoverPhoto.setBounds(50, 130, 290, 280);

        getContentPane().add(jPanelWhite);
        jPanelWhite.setBounds(0, 0, 940, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void setLoginImage() {
        jLabelLoginCoverPhoto.setIcon(new javax.swing.ImageIcon("src\\images\\mphLoginPhoto.png"));
    }
    
    
    private boolean authenticateCredentials(String username, String password) {
        String fileName = "src\\csv\\files\\redacted.csv"; //csv for the password and user name
        CSVReader reader = null;
        String[] credentials;

        try {
            reader = new CSVReader(new FileReader(fileName));
            reader.readNext(); // Skip header
            
            while ((credentials = reader.readNext()) != null) {
                if (credentials.length >= 2) {
                    String csvUsername = credentials[0].trim();
                    String csvPassword = credentials[1].trim();

                    if (csvUsername.equals(username) && csvPassword.equals(password)) {
                        return true;
                    }
                }
            }
        } catch (IOException ex) {
            ex.printStackTrace();
        } finally {
            if (reader != null) {
                try {
                    reader.close();
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
            }
        } 
        
        return false;
    }
    
    
    private void proceedToMainView() {
        this.setVisible(false);
        RecordsPage recordsPage = new RecordsPage();
        recordsPage.setVisible(true);
    }
    
    
    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        String username = jTextFieldUsername.getText();
        String password = new String(jPassword.getPassword());

        if (authenticateCredentials(username, password)) {
            proceedToMainView(); 
        } else {
            JOptionPane.showMessageDialog(this, "Invalid username or password", "Login Failed", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jTextFieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsernameActionPerformed

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JLabel jLabelLoginCoverPhoto;
    private javax.swing.JLabel jLabelMotorph;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JPanel jPanelWhite;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
