package gui.frames;


import classes.Employee;
import com.opencsv.CSVReader;
import java.io.FileReader;
import java.io.IOException;
import java.time.format.DateTimeFormatter;
import javax.swing.JFrame;


public final class PayslipPage extends javax.swing.JFrame {
    
    private final int employeeNumber;
    private final String startDate;
    private final String endDate;
    
    /**
     * Creates new form PayslipPageNew
     */
    
    public PayslipPage(int employeeNumber, String startDate, String endDate, int daysWorked) {
        initComponents();
        this.employeeNumber = employeeNumber;
        this.startDate = startDate;
        this.endDate = endDate;
        updateWorkPeriodTextField(startDate, endDate);
        updateDaysWorkedTextField(daysWorked);
        int hoursWorked = getHoursWorked(daysWorked);
        double grossIncome = calculateGrossIncome(hoursWorked);
        double totalBenefits = getTotalBenefits();
        double sssContribution = calculateSSS(grossIncome);
        double philHealthContribution = calculatePhilHealth(grossIncome);
        double pagIbigContribution = calculatePagIbig(grossIncome);
        double totalContributions = calculateTotalContributions(sssContribution, philHealthContribution, pagIbigContribution);
        double taxableIncome = calculateTaxableIncome(grossIncome, totalContributions);
        double withholdingTax = calculateWithholdingTax(taxableIncome);
        double netIncome = calculateNetIncome(taxableIncome, withholdingTax);
        calculateTotalDeductions(totalContributions, withholdingTax);
        populatePayslip(grossIncome, totalContributions, taxableIncome, totalBenefits, netIncome);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBody = new javax.swing.JPanel();
        jPanelBottomBorder = new javax.swing.JPanel();
        jPanelDetails = new javax.swing.JPanel();
        jLabelDetails = new javax.swing.JLabel();
        jLabelEmployeeNo = new javax.swing.JLabel();
        jTextFieldEmployeeNo = new javax.swing.JTextField();
        jLabelLastName = new javax.swing.JLabel();
        jTextFieldLastName = new javax.swing.JTextField();
        jLabelFirstName = new javax.swing.JLabel();
        jTextFieldFirstName = new javax.swing.JTextField();
        jLabelBirthday = new javax.swing.JLabel();
        jTextFieldBirthday = new javax.swing.JTextField();
        jLabelPhoneNo = new javax.swing.JLabel();
        jTextFieldPhoneNo = new javax.swing.JTextField();
        jLabelStatus = new javax.swing.JLabel();
        jTextFieldStatus = new javax.swing.JTextField();
        jLabelDepartment = new javax.swing.JLabel();
        jTextFieldDepartment = new javax.swing.JTextField();
        jLabelPosition = new javax.swing.JLabel();
        jTextFieldPosition = new javax.swing.JTextField();
        jLabelSupervisor = new javax.swing.JLabel();
        jTextFieldSupervisor = new javax.swing.JTextField();
        jLabelSssNo = new javax.swing.JLabel();
        jTextFieldSssNo = new javax.swing.JTextField();
        jLabelPhilHealthNo = new javax.swing.JLabel();
        jTextFieldPhilHealthNo = new javax.swing.JTextField();
        jLabelTin = new javax.swing.JLabel();
        jTextFieldTin = new javax.swing.JTextField();
        jLabelPagIbigNo = new javax.swing.JLabel();
        jTextFieldPagIbigNo = new javax.swing.JTextField();
        jLabelPayslipNo = new javax.swing.JLabel();
        jTextFieldPayslipNo = new javax.swing.JTextField();
        jLabelPayType = new javax.swing.JLabel();
        jTextFieldPayType = new javax.swing.JTextField();
        jLabelWorkEndDate = new javax.swing.JLabel();
        jTextFieldWorkPeriod = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanelApplyTax = new javax.swing.JPanel();
        jLabelApplyTax = new javax.swing.JLabel();
        jTextFieldTaxableIncome2 = new javax.swing.JTextField();
        jLabelTaxableIncome2 = new javax.swing.JLabel();
        jTextFieldWithholdingTax = new javax.swing.JTextField();
        jLabelWithholdingTax = new javax.swing.JLabel();
        jTextFieldNetIncome = new javax.swing.JTextField();
        jLabelNetIncome = new javax.swing.JLabel();
        jPanelEarnings = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabelEarnings = new javax.swing.JLabel();
        jLabelBasicSalary = new javax.swing.JLabel();
        jTextFieldBasicSalary = new javax.swing.JTextField();
        jLabelDaysWorked = new javax.swing.JLabel();
        jTextFieldDaysWorked = new javax.swing.JTextField();
        jLabelHourlyRate = new javax.swing.JLabel();
        jTextFieldHourlyRate = new javax.swing.JTextField();
        jLabelHoursWorked = new javax.swing.JLabel();
        jTextFieldHoursWorked = new javax.swing.JTextField();
        jLabelGrossIncome = new javax.swing.JLabel();
        jTextFieldGrossIncome = new javax.swing.JTextField();
        jPanelBenefits = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabelBenefits = new javax.swing.JLabel();
        jLabelRiceSubsidy = new javax.swing.JLabel();
        jTextFieldRiceSubsidy = new javax.swing.JTextField();
        jLabelPhoneAllowance = new javax.swing.JLabel();
        jTextFieldPhoneAllowance = new javax.swing.JTextField();
        jLabelClothingAllowance = new javax.swing.JLabel();
        jTextFieldClothingAllowance = new javax.swing.JTextField();
        jLabelTotalBenefits = new javax.swing.JLabel();
        jTextFieldTotalBenefits = new javax.swing.JTextField();
        jPanelContributions = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabelContributions = new javax.swing.JLabel();
        jLabelSssContribution = new javax.swing.JLabel();
        jTextFieldSssContribution = new javax.swing.JTextField();
        jTextFieldPhilHealthContribution = new javax.swing.JTextField();
        jLabelPhilHealthContribution = new javax.swing.JLabel();
        jTextFieldPagIbigContribution = new javax.swing.JTextField();
        jLabelPagIbigContribution = new javax.swing.JLabel();
        jTextFieldTotalContributions = new javax.swing.JTextField();
        jLabelTotalContributions = new javax.swing.JLabel();
        jPanelTaxableIncome = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabelTaxableIncome = new javax.swing.JLabel();
        jTextFieldGrossIncome2 = new javax.swing.JTextField();
        jLabelGrossIncome2 = new javax.swing.JLabel();
        jTextFieldTotalContributions2 = new javax.swing.JTextField();
        jLabelTotalContributions2 = new javax.swing.JLabel();
        jTextFieldTaxableIncome = new javax.swing.JTextField();
        jLabelTotalTaxableIncome = new javax.swing.JLabel();
        jPanelSummary = new javax.swing.JPanel();
        jLabelSummary = new javax.swing.JLabel();
        jTextFieldGrossIncome3 = new javax.swing.JTextField();
        jLabelGrossIncome3 = new javax.swing.JLabel();
        jTextFieldTotalBenefits2 = new javax.swing.JTextField();
        jLabelTotalBenefits2 = new javax.swing.JLabel();
        jTextFieldTotalDeductions = new javax.swing.JTextField();
        jLabelTotalDeductions = new javax.swing.JLabel();
        jTextFieldTakeHomePay = new javax.swing.JTextField();
        jLabelTakeHomePay = new javax.swing.JLabel();
        jPanelBottomBorder1 = new javax.swing.JPanel();
        jPanelBottomBorder2 = new javax.swing.JPanel();
        jButtonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 719));
        setMinimumSize(new java.awt.Dimension(1280, 719));

        jPanelBody.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBody.setLayout(null);

        jPanelBottomBorder.setBackground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout jPanelBottomBorderLayout = new javax.swing.GroupLayout(jPanelBottomBorder);
        jPanelBottomBorder.setLayout(jPanelBottomBorderLayout);
        jPanelBottomBorderLayout.setHorizontalGroup(
            jPanelBottomBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        jPanelBottomBorderLayout.setVerticalGroup(
            jPanelBottomBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanelBody.add(jPanelBottomBorder);
        jPanelBottomBorder.setBounds(0, 660, 1280, 10);

        jPanelDetails.setBackground(new java.awt.Color(228, 233, 239));
        jPanelDetails.setLayout(null);

        jLabelDetails.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelDetails.setText("Details");
        jPanelDetails.add(jLabelDetails);
        jLabelDetails.setBounds(20, 30, 70, 30);

        jLabelEmployeeNo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelEmployeeNo.setText("Employee No.    :");
        jPanelDetails.add(jLabelEmployeeNo);
        jLabelEmployeeNo.setBounds(10, 190, 100, 30);

        jTextFieldEmployeeNo.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldEmployeeNo.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldEmployeeNo.setEnabled(false);
        jTextFieldEmployeeNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmployeeNoActionPerformed(evt);
            }
        });
        jPanelDetails.add(jTextFieldEmployeeNo);
        jTextFieldEmployeeNo.setBounds(120, 190, 170, 30);

        jLabelLastName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelLastName.setText("Last Name          : ");
        jPanelDetails.add(jLabelLastName);
        jLabelLastName.setBounds(20, 220, 100, 30);

        jTextFieldLastName.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldLastName.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldLastName.setEnabled(false);
        jTextFieldLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLastNameActionPerformed(evt);
            }
        });
        jPanelDetails.add(jTextFieldLastName);
        jTextFieldLastName.setBounds(120, 220, 170, 30);

        jLabelFirstName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelFirstName.setText("First Name         :");
        jPanelDetails.add(jLabelFirstName);
        jLabelFirstName.setBounds(10, 250, 100, 30);

        jTextFieldFirstName.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldFirstName.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldFirstName.setEnabled(false);
        jTextFieldFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFirstNameActionPerformed(evt);
            }
        });
        jPanelDetails.add(jTextFieldFirstName);
        jTextFieldFirstName.setBounds(120, 250, 170, 30);

        jLabelBirthday.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelBirthday.setText("Date of Birth       :");
        jPanelDetails.add(jLabelBirthday);
        jLabelBirthday.setBounds(10, 280, 100, 30);

        jTextFieldBirthday.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldBirthday.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldBirthday.setEnabled(false);
        jTextFieldBirthday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBirthdayActionPerformed(evt);
            }
        });
        jPanelDetails.add(jTextFieldBirthday);
        jTextFieldBirthday.setBounds(120, 280, 170, 30);

        jLabelPhoneNo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPhoneNo.setText("Phone No.          :");
        jPanelDetails.add(jLabelPhoneNo);
        jLabelPhoneNo.setBounds(10, 310, 100, 30);

        jTextFieldPhoneNo.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldPhoneNo.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldPhoneNo.setEnabled(false);
        jTextFieldPhoneNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPhoneNoActionPerformed(evt);
            }
        });
        jPanelDetails.add(jTextFieldPhoneNo);
        jTextFieldPhoneNo.setBounds(120, 310, 170, 30);

        jLabelStatus.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelStatus.setText("Status                 :");
        jPanelDetails.add(jLabelStatus);
        jLabelStatus.setBounds(20, 340, 90, 30);

        jTextFieldStatus.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldStatus.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldStatus.setEnabled(false);
        jTextFieldStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldStatusActionPerformed(evt);
            }
        });
        jPanelDetails.add(jTextFieldStatus);
        jTextFieldStatus.setBounds(120, 340, 170, 30);

        jLabelDepartment.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDepartment.setText("Department       :");
        jPanelDetails.add(jLabelDepartment);
        jLabelDepartment.setBounds(10, 370, 100, 30);

        jTextFieldDepartment.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldDepartment.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldDepartment.setEnabled(false);
        jTextFieldDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDepartmentActionPerformed(evt);
            }
        });
        jPanelDetails.add(jTextFieldDepartment);
        jTextFieldDepartment.setBounds(120, 370, 170, 30);

        jLabelPosition.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPosition.setText("Position             :");
        jPanelDetails.add(jLabelPosition);
        jLabelPosition.setBounds(10, 400, 100, 30);

        jTextFieldPosition.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldPosition.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldPosition.setEnabled(false);
        jTextFieldPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPositionActionPerformed(evt);
            }
        });
        jPanelDetails.add(jTextFieldPosition);
        jTextFieldPosition.setBounds(120, 400, 170, 30);

        jLabelSupervisor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelSupervisor.setText("Supervisor         :");
        jPanelDetails.add(jLabelSupervisor);
        jLabelSupervisor.setBounds(10, 430, 100, 30);

        jTextFieldSupervisor.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldSupervisor.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldSupervisor.setEnabled(false);
        jTextFieldSupervisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSupervisorActionPerformed(evt);
            }
        });
        jPanelDetails.add(jTextFieldSupervisor);
        jTextFieldSupervisor.setBounds(120, 430, 170, 30);

        jLabelSssNo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelSssNo.setText("SSS No.             :");
        jPanelDetails.add(jLabelSssNo);
        jLabelSssNo.setBounds(10, 460, 100, 30);

        jTextFieldSssNo.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldSssNo.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldSssNo.setEnabled(false);
        jTextFieldSssNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSssNoActionPerformed(evt);
            }
        });
        jPanelDetails.add(jTextFieldSssNo);
        jTextFieldSssNo.setBounds(120, 460, 170, 30);

        jLabelPhilHealthNo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPhilHealthNo.setText("PhilHealth No.  :");
        jPanelDetails.add(jLabelPhilHealthNo);
        jLabelPhilHealthNo.setBounds(20, 490, 90, 30);

        jTextFieldPhilHealthNo.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldPhilHealthNo.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldPhilHealthNo.setEnabled(false);
        jTextFieldPhilHealthNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPhilHealthNoActionPerformed(evt);
            }
        });
        jPanelDetails.add(jTextFieldPhilHealthNo);
        jTextFieldPhilHealthNo.setBounds(120, 490, 170, 30);

        jLabelTin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTin.setText("TIN                      :");
        jPanelDetails.add(jLabelTin);
        jLabelTin.setBounds(10, 520, 100, 30);

        jTextFieldTin.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldTin.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldTin.setEnabled(false);
        jTextFieldTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTinActionPerformed(evt);
            }
        });
        jPanelDetails.add(jTextFieldTin);
        jTextFieldTin.setBounds(120, 520, 170, 30);

        jLabelPagIbigNo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPagIbigNo.setText("Pag-Ibig No.     :");
        jPanelDetails.add(jLabelPagIbigNo);
        jLabelPagIbigNo.setBounds(10, 550, 100, 30);

        jTextFieldPagIbigNo.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldPagIbigNo.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldPagIbigNo.setEnabled(false);
        jTextFieldPagIbigNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPagIbigNoActionPerformed(evt);
            }
        });
        jPanelDetails.add(jTextFieldPagIbigNo);
        jTextFieldPagIbigNo.setBounds(120, 550, 170, 30);

        jLabelPayslipNo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPayslipNo.setText("Payslip No.        :");
        jPanelDetails.add(jLabelPayslipNo);
        jLabelPayslipNo.setBounds(20, 80, 90, 30);

        jTextFieldPayslipNo.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldPayslipNo.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldPayslipNo.setEnabled(false);
        jTextFieldPayslipNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPayslipNoActionPerformed(evt);
            }
        });
        jPanelDetails.add(jTextFieldPayslipNo);
        jTextFieldPayslipNo.setBounds(120, 80, 170, 30);

        jLabelPayType.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPayType.setText("Pay Type            :");
        jPanelDetails.add(jLabelPayType);
        jLabelPayType.setBounds(20, 110, 90, 30);

        jTextFieldPayType.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldPayType.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldPayType.setEnabled(false);
        jTextFieldPayType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPayTypeActionPerformed(evt);
            }
        });
        jPanelDetails.add(jTextFieldPayType);
        jTextFieldPayType.setBounds(120, 110, 170, 30);

        jLabelWorkEndDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelWorkEndDate.setText("Work Period      :");
        jPanelDetails.add(jLabelWorkEndDate);
        jLabelWorkEndDate.setBounds(20, 140, 90, 30);

        jTextFieldWorkPeriod.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldWorkPeriod.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldWorkPeriod.setEnabled(false);
        jTextFieldWorkPeriod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldWorkPeriodActionPerformed(evt);
            }
        });
        jPanelDetails.add(jTextFieldWorkPeriod);
        jTextFieldWorkPeriod.setBounds(120, 140, 170, 30);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanelDetails.add(jPanel1);
        jPanel1.setBounds(50, -10, 130, 10);

        jPanelBody.add(jPanelDetails);
        jPanelDetails.setBounds(0, 10, 300, 660);

        jPanelApplyTax.setBackground(new java.awt.Color(228, 233, 239));
        jPanelApplyTax.setLayout(null);

        jLabelApplyTax.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelApplyTax.setText("Apply Tax");
        jPanelApplyTax.add(jLabelApplyTax);
        jLabelApplyTax.setBounds(30, 30, 110, 30);

        jTextFieldTaxableIncome2.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldTaxableIncome2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldTaxableIncome2.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldTaxableIncome2.setEnabled(false);
        jTextFieldTaxableIncome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTaxableIncome2ActionPerformed(evt);
            }
        });
        jPanelApplyTax.add(jTextFieldTaxableIncome2);
        jTextFieldTaxableIncome2.setBounds(140, 80, 160, 30);

        jLabelTaxableIncome2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTaxableIncome2.setText("Taxable Income    :");
        jPanelApplyTax.add(jLabelTaxableIncome2);
        jLabelTaxableIncome2.setBounds(20, 80, 110, 30);

        jTextFieldWithholdingTax.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldWithholdingTax.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldWithholdingTax.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldWithholdingTax.setEnabled(false);
        jTextFieldWithholdingTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldWithholdingTaxActionPerformed(evt);
            }
        });
        jPanelApplyTax.add(jTextFieldWithholdingTax);
        jTextFieldWithholdingTax.setBounds(140, 110, 160, 30);

        jLabelWithholdingTax.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelWithholdingTax.setText("Withholding Tax    :");
        jPanelApplyTax.add(jLabelWithholdingTax);
        jLabelWithholdingTax.setBounds(10, 110, 120, 30);

        jTextFieldNetIncome.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldNetIncome.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldNetIncome.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldNetIncome.setEnabled(false);
        jTextFieldNetIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNetIncomeActionPerformed(evt);
            }
        });
        jPanelApplyTax.add(jTextFieldNetIncome);
        jTextFieldNetIncome.setBounds(140, 230, 160, 30);

        jLabelNetIncome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelNetIncome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNetIncome.setText("NET INCOME          :");
        jPanelApplyTax.add(jLabelNetIncome);
        jLabelNetIncome.setBounds(10, 230, 120, 30);

        jPanelBody.add(jPanelApplyTax);
        jPanelApplyTax.setBounds(950, 10, 320, 290);

        jPanelEarnings.setBackground(new java.awt.Color(228, 233, 239));
        jPanelEarnings.setLayout(null);

        jPanel16.setBackground(new java.awt.Color(218, 235, 219));
        jPanel16.setLayout(null);
        jPanelEarnings.add(jPanel16);
        jPanel16.setBounds(310, 0, 320, 330);

        jLabelEarnings.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelEarnings.setText("Earnings");
        jPanelEarnings.add(jLabelEarnings);
        jLabelEarnings.setBounds(30, 30, 90, 30);

        jLabelBasicSalary.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelBasicSalary.setText("Basic Salary         :");
        jPanelEarnings.add(jLabelBasicSalary);
        jLabelBasicSalary.setBounds(30, 80, 100, 30);

        jTextFieldBasicSalary.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldBasicSalary.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldBasicSalary.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldBasicSalary.setEnabled(false);
        jTextFieldBasicSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBasicSalaryActionPerformed(evt);
            }
        });
        jPanelEarnings.add(jTextFieldBasicSalary);
        jTextFieldBasicSalary.setBounds(140, 80, 160, 30);

        jLabelDaysWorked.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDaysWorked.setText("Days Worked       :");
        jPanelEarnings.add(jLabelDaysWorked);
        jLabelDaysWorked.setBounds(30, 110, 100, 30);

        jTextFieldDaysWorked.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldDaysWorked.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldDaysWorked.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldDaysWorked.setEnabled(false);
        jTextFieldDaysWorked.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDaysWorkedActionPerformed(evt);
            }
        });
        jPanelEarnings.add(jTextFieldDaysWorked);
        jTextFieldDaysWorked.setBounds(140, 110, 160, 30);

        jLabelHourlyRate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelHourlyRate.setText("Hourly Rate          :");
        jPanelEarnings.add(jLabelHourlyRate);
        jLabelHourlyRate.setBounds(30, 140, 100, 30);

        jTextFieldHourlyRate.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldHourlyRate.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldHourlyRate.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldHourlyRate.setEnabled(false);
        jTextFieldHourlyRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHourlyRateActionPerformed(evt);
            }
        });
        jPanelEarnings.add(jTextFieldHourlyRate);
        jTextFieldHourlyRate.setBounds(140, 140, 160, 30);

        jLabelHoursWorked.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelHoursWorked.setText("Hours Worked     :");
        jPanelEarnings.add(jLabelHoursWorked);
        jLabelHoursWorked.setBounds(30, 170, 100, 30);

        jTextFieldHoursWorked.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldHoursWorked.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldHoursWorked.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldHoursWorked.setEnabled(false);
        jTextFieldHoursWorked.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHoursWorkedActionPerformed(evt);
            }
        });
        jPanelEarnings.add(jTextFieldHoursWorked);
        jTextFieldHoursWorked.setBounds(140, 170, 160, 30);

        jLabelGrossIncome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelGrossIncome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelGrossIncome.setText("GROSS INCOME  :");
        jPanelEarnings.add(jLabelGrossIncome);
        jLabelGrossIncome.setBounds(20, 230, 110, 30);

        jTextFieldGrossIncome.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldGrossIncome.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldGrossIncome.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldGrossIncome.setEnabled(false);
        jTextFieldGrossIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGrossIncomeActionPerformed(evt);
            }
        });
        jPanelEarnings.add(jTextFieldGrossIncome);
        jTextFieldGrossIncome.setBounds(140, 230, 160, 30);

        jPanelBody.add(jPanelEarnings);
        jPanelEarnings.setBounds(310, 10, 310, 290);

        jPanelBenefits.setBackground(new java.awt.Color(228, 233, 239));
        jPanelBenefits.setLayout(null);

        jPanel18.setBackground(new java.awt.Color(218, 235, 219));
        jPanel18.setLayout(null);
        jPanelBenefits.add(jPanel18);
        jPanel18.setBounds(310, 0, 320, 330);

        jLabelBenefits.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelBenefits.setText("Benefits");
        jPanelBenefits.add(jLabelBenefits);
        jLabelBenefits.setBounds(20, 30, 80, 30);

        jLabelRiceSubsidy.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelRiceSubsidy.setText("Rice Subsidy            :");
        jPanelBenefits.add(jLabelRiceSubsidy);
        jLabelRiceSubsidy.setBounds(0, 80, 130, 30);

        jTextFieldRiceSubsidy.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldRiceSubsidy.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldRiceSubsidy.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldRiceSubsidy.setEnabled(false);
        jTextFieldRiceSubsidy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRiceSubsidyActionPerformed(evt);
            }
        });
        jPanelBenefits.add(jTextFieldRiceSubsidy);
        jTextFieldRiceSubsidy.setBounds(140, 80, 160, 30);

        jLabelPhoneAllowance.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPhoneAllowance.setText("Phone Allowance    :");
        jPanelBenefits.add(jLabelPhoneAllowance);
        jLabelPhoneAllowance.setBounds(0, 110, 130, 30);

        jTextFieldPhoneAllowance.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldPhoneAllowance.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldPhoneAllowance.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldPhoneAllowance.setEnabled(false);
        jTextFieldPhoneAllowance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPhoneAllowanceActionPerformed(evt);
            }
        });
        jPanelBenefits.add(jTextFieldPhoneAllowance);
        jTextFieldPhoneAllowance.setBounds(140, 110, 160, 30);

        jLabelClothingAllowance.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelClothingAllowance.setText("Clothing Allowance :");
        jPanelBenefits.add(jLabelClothingAllowance);
        jLabelClothingAllowance.setBounds(10, 140, 120, 30);

        jTextFieldClothingAllowance.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldClothingAllowance.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldClothingAllowance.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldClothingAllowance.setEnabled(false);
        jTextFieldClothingAllowance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldClothingAllowanceActionPerformed(evt);
            }
        });
        jPanelBenefits.add(jTextFieldClothingAllowance);
        jTextFieldClothingAllowance.setBounds(140, 140, 160, 30);

        jLabelTotalBenefits.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTotalBenefits.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTotalBenefits.setText("TOTAL                       :");
        jPanelBenefits.add(jLabelTotalBenefits);
        jLabelTotalBenefits.setBounds(0, 200, 130, 30);

        jTextFieldTotalBenefits.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldTotalBenefits.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldTotalBenefits.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldTotalBenefits.setEnabled(false);
        jTextFieldTotalBenefits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalBenefitsActionPerformed(evt);
            }
        });
        jPanelBenefits.add(jTextFieldTotalBenefits);
        jTextFieldTotalBenefits.setBounds(140, 200, 160, 30);

        jPanelBody.add(jPanelBenefits);
        jPanelBenefits.setBounds(310, 310, 310, 260);

        jPanelContributions.setBackground(new java.awt.Color(228, 233, 239));
        jPanelContributions.setLayout(null);

        jPanel20.setBackground(new java.awt.Color(218, 235, 219));
        jPanel20.setLayout(null);
        jPanelContributions.add(jPanel20);
        jPanel20.setBounds(310, 0, 320, 330);

        jLabelContributions.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelContributions.setText("Contributions");
        jPanelContributions.add(jLabelContributions);
        jLabelContributions.setBounds(40, 30, 140, 30);

        jLabelSssContribution.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelSssContribution.setText("SSS                 :");
        jPanelContributions.add(jLabelSssContribution);
        jLabelSssContribution.setBounds(30, 80, 90, 30);

        jTextFieldSssContribution.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldSssContribution.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldSssContribution.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldSssContribution.setEnabled(false);
        jTextFieldSssContribution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSssContributionActionPerformed(evt);
            }
        });
        jPanelContributions.add(jTextFieldSssContribution);
        jTextFieldSssContribution.setBounds(140, 80, 160, 30);

        jTextFieldPhilHealthContribution.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldPhilHealthContribution.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldPhilHealthContribution.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldPhilHealthContribution.setEnabled(false);
        jTextFieldPhilHealthContribution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPhilHealthContributionActionPerformed(evt);
            }
        });
        jPanelContributions.add(jTextFieldPhilHealthContribution);
        jTextFieldPhilHealthContribution.setBounds(140, 110, 160, 30);

        jLabelPhilHealthContribution.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPhilHealthContribution.setText("PhilHealth      :");
        jPanelContributions.add(jLabelPhilHealthContribution);
        jLabelPhilHealthContribution.setBounds(30, 110, 90, 30);

        jTextFieldPagIbigContribution.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldPagIbigContribution.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldPagIbigContribution.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldPagIbigContribution.setEnabled(false);
        jTextFieldPagIbigContribution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPagIbigContributionActionPerformed(evt);
            }
        });
        jPanelContributions.add(jTextFieldPagIbigContribution);
        jTextFieldPagIbigContribution.setBounds(140, 140, 160, 30);

        jLabelPagIbigContribution.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPagIbigContribution.setText("Pag-Ibig          :");
        jPanelContributions.add(jLabelPagIbigContribution);
        jLabelPagIbigContribution.setBounds(30, 140, 90, 30);

        jTextFieldTotalContributions.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldTotalContributions.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldTotalContributions.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldTotalContributions.setEnabled(false);
        jTextFieldTotalContributions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalContributionsActionPerformed(evt);
            }
        });
        jPanelContributions.add(jTextFieldTotalContributions);
        jTextFieldTotalContributions.setBounds(140, 230, 160, 30);

        jLabelTotalContributions.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTotalContributions.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTotalContributions.setText("TOTAL            :");
        jPanelContributions.add(jLabelTotalContributions);
        jLabelTotalContributions.setBounds(30, 230, 90, 30);

        jPanelBody.add(jPanelContributions);
        jPanelContributions.setBounds(630, 10, 310, 290);

        jPanelTaxableIncome.setBackground(new java.awt.Color(228, 233, 239));
        jPanelTaxableIncome.setLayout(null);

        jPanel22.setBackground(new java.awt.Color(218, 235, 219));
        jPanel22.setLayout(null);
        jPanelTaxableIncome.add(jPanel22);
        jPanel22.setBounds(310, 0, 320, 330);

        jLabelTaxableIncome.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTaxableIncome.setText("Taxable Income");
        jPanelTaxableIncome.add(jLabelTaxableIncome);
        jLabelTaxableIncome.setBounds(20, 30, 160, 30);

        jTextFieldGrossIncome2.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldGrossIncome2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldGrossIncome2.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldGrossIncome2.setEnabled(false);
        jTextFieldGrossIncome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGrossIncome2ActionPerformed(evt);
            }
        });
        jPanelTaxableIncome.add(jTextFieldGrossIncome2);
        jTextFieldGrossIncome2.setBounds(140, 80, 160, 30);

        jLabelGrossIncome2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelGrossIncome2.setText("Gross Income          :");
        jPanelTaxableIncome.add(jLabelGrossIncome2);
        jLabelGrossIncome2.setBounds(0, 80, 130, 30);

        jTextFieldTotalContributions2.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldTotalContributions2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldTotalContributions2.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldTotalContributions2.setEnabled(false);
        jTextFieldTotalContributions2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalContributions2ActionPerformed(evt);
            }
        });
        jPanelTaxableIncome.add(jTextFieldTotalContributions2);
        jTextFieldTotalContributions2.setBounds(140, 110, 160, 30);

        jLabelTotalContributions2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTotalContributions2.setText("Total Contributions :");
        jPanelTaxableIncome.add(jLabelTotalContributions2);
        jLabelTotalContributions2.setBounds(10, 110, 120, 30);

        jTextFieldTaxableIncome.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldTaxableIncome.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldTaxableIncome.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldTaxableIncome.setEnabled(false);
        jTextFieldTaxableIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTaxableIncomeActionPerformed(evt);
            }
        });
        jPanelTaxableIncome.add(jTextFieldTaxableIncome);
        jTextFieldTaxableIncome.setBounds(140, 200, 160, 30);

        jLabelTotalTaxableIncome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTotalTaxableIncome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTotalTaxableIncome.setText("TAXABLE INCOME  :");
        jPanelTaxableIncome.add(jLabelTotalTaxableIncome);
        jLabelTotalTaxableIncome.setBounds(10, 200, 120, 30);

        jPanelBody.add(jPanelTaxableIncome);
        jPanelTaxableIncome.setBounds(630, 310, 310, 260);

        jPanelSummary.setBackground(new java.awt.Color(228, 233, 239));
        jPanelSummary.setLayout(null);

        jLabelSummary.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelSummary.setText("Summary");
        jPanelSummary.add(jLabelSummary);
        jLabelSummary.setBounds(30, 30, 100, 30);

        jTextFieldGrossIncome3.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldGrossIncome3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldGrossIncome3.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldGrossIncome3.setEnabled(false);
        jTextFieldGrossIncome3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGrossIncome3ActionPerformed(evt);
            }
        });
        jPanelSummary.add(jTextFieldGrossIncome3);
        jTextFieldGrossIncome3.setBounds(140, 80, 160, 30);

        jLabelGrossIncome3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelGrossIncome3.setText("Gross Income      :");
        jPanelSummary.add(jLabelGrossIncome3);
        jLabelGrossIncome3.setBounds(20, 80, 110, 30);

        jTextFieldTotalBenefits2.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldTotalBenefits2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldTotalBenefits2.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldTotalBenefits2.setEnabled(false);
        jTextFieldTotalBenefits2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalBenefits2ActionPerformed(evt);
            }
        });
        jPanelSummary.add(jTextFieldTotalBenefits2);
        jTextFieldTotalBenefits2.setBounds(140, 110, 160, 30);

        jLabelTotalBenefits2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTotalBenefits2.setText("Total Benefits       :");
        jPanelSummary.add(jLabelTotalBenefits2);
        jLabelTotalBenefits2.setBounds(20, 110, 110, 30);

        jTextFieldTotalDeductions.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldTotalDeductions.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldTotalDeductions.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldTotalDeductions.setEnabled(false);
        jTextFieldTotalDeductions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalDeductionsActionPerformed(evt);
            }
        });
        jPanelSummary.add(jTextFieldTotalDeductions);
        jTextFieldTotalDeductions.setBounds(140, 140, 160, 30);

        jLabelTotalDeductions.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTotalDeductions.setText("Total Deductions :");
        jPanelSummary.add(jLabelTotalDeductions);
        jLabelTotalDeductions.setBounds(20, 140, 110, 30);

        jTextFieldTakeHomePay.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldTakeHomePay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldTakeHomePay.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldTakeHomePay.setEnabled(false);
        jTextFieldTakeHomePay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTakeHomePayActionPerformed(evt);
            }
        });
        jPanelSummary.add(jTextFieldTakeHomePay);
        jTextFieldTakeHomePay.setBounds(140, 200, 160, 30);

        jLabelTakeHomePay.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTakeHomePay.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTakeHomePay.setText("TAKE HOME PAY :");
        jPanelSummary.add(jLabelTakeHomePay);
        jLabelTakeHomePay.setBounds(20, 200, 110, 30);

        jPanelBody.add(jPanelSummary);
        jPanelSummary.setBounds(950, 310, 320, 260);

        jPanelBottomBorder1.setBackground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout jPanelBottomBorder1Layout = new javax.swing.GroupLayout(jPanelBottomBorder1);
        jPanelBottomBorder1.setLayout(jPanelBottomBorder1Layout);
        jPanelBottomBorder1Layout.setHorizontalGroup(
            jPanelBottomBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        jPanelBottomBorder1Layout.setVerticalGroup(
            jPanelBottomBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanelBody.add(jPanelBottomBorder1);
        jPanelBottomBorder1.setBounds(-10, 0, 1280, 10);

        jPanelBottomBorder2.setBackground(new java.awt.Color(228, 233, 239));
        jPanelBottomBorder2.setLayout(null);

        jButtonBack.setBackground(new java.awt.Color(204, 0, 0));
        jButtonBack.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        jPanelBottomBorder2.add(jButtonBack);
        jButtonBack.setBounds(790, 20, 150, 40);

        jPanelBody.add(jPanelBottomBorder2);
        jPanelBottomBorder2.setBounds(310, 580, 980, 80);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelBody, javax.swing.GroupLayout.PREFERRED_SIZE, 1270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelBody, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void populatePayslip(double grossIncome, double totalContributions, double taxableIncome, double totalBenefits, double netIncome) {
        Employee employee = Employee.getEmployeeByNumber(employeeNumber);
        if (employee != null) {
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("MM/dd/yyyy");
            jTextFieldEmployeeNo.setText(String.valueOf(employee.getEmployeeNumber()));
            jTextFieldLastName.setText(employee.getLastName());
            jTextFieldFirstName.setText(employee.getFirstName());
            jTextFieldBirthday.setText(employee.getBirthday().format(formatter));
            jTextFieldPhoneNo.setText(employee.getPhoneNumber());
            jTextFieldStatus.setText(employee.getStatus());
            jTextFieldDepartment.setText(employee.getDepartment());
            jTextFieldPosition.setText(employee.getPosition());
            jTextFieldSupervisor.setText(employee.getImmediateSupervisor());
            jTextFieldSssNo.setText(employee.getSssNumber());
            jTextFieldPhilHealthNo.setText(employee.getPhilHealthNumber());
            jTextFieldTin.setText(employee.getTinNumber());
            jTextFieldPagIbigNo.setText(employee.getPagIbigNumber());
            jTextFieldBasicSalary.setText(String.format("%.2f", employee.getBasicSalary()));
            jTextFieldRiceSubsidy.setText(String.format("%.2f", employee.getRiceSubsidy()));
            jTextFieldPhoneAllowance.setText(String.format("%.2f", employee.getPhoneAllowance()));
            jTextFieldClothingAllowance.setText(String.format("%.2f", employee.getClothingAllowance()));
            jTextFieldHourlyRate.setText(String.format("%.2f", employee.getHourlyRate()));
            jTextFieldPayslipNo.setText(String.valueOf(employee.getEmployeeNumber()) + "-2022-2024");
            jTextFieldPayType.setText("Monthly");
            jTextFieldGrossIncome2.setText(String.format("%.2f", grossIncome));
            jTextFieldTotalContributions2.setText(String.format("%.2f", totalContributions));
            jTextFieldTaxableIncome2.setText(String.format("%.2f", taxableIncome));
            jTextFieldGrossIncome3.setText(String.format("%.2f", grossIncome));
            jTextFieldTotalBenefits2.setText(String.format("%.2f", totalBenefits));
            jTextFieldTakeHomePay.setText(String.format("%.2f", netIncome));
        }
    }
    
    
    public void updateWorkPeriodTextField(String startDate, String endDate) {
        String formattedDateRange = String.format("%s - %s", startDate, endDate);
        jTextFieldWorkPeriod.setText(formattedDateRange);
    }
    
    
    public void updateDaysWorkedTextField(int daysWorked) {
        jTextFieldDaysWorked.setText(String.valueOf(daysWorked));
    }
    
    
    public int getHoursWorked(int daysWorked) {
        int hoursWorked = daysWorked * 8;
        jTextFieldHoursWorked.setText(String.valueOf(hoursWorked));
        return hoursWorked;
    }
    
    
    public double calculateGrossIncome(int hoursWorked) {
        Employee employee = Employee.getEmployeeByNumber(employeeNumber);
        double grossIncome = hoursWorked * employee.getHourlyRate();
        jTextFieldGrossIncome.setText(String.format("%.2f", grossIncome));
        return grossIncome;
    }
    
    
    public double getTotalBenefits() {
        Employee employee = Employee.getEmployeeByNumber(employeeNumber);
        double totalBenefits = employee.getRiceSubsidy() + employee.getPhoneAllowance() + employee.getClothingAllowance();
        jTextFieldTotalBenefits.setText(String.format("%.2f", totalBenefits));
        return totalBenefits;
    }
    
    
    public double calculateSSS(double grossIncome) {
        CSVReader reader = null;
        String fileName = "src\\csv\\files\\sssContribution.csv";
        double sssContribution = 0;

        try {
            reader = new CSVReader(new FileReader(fileName));
            reader.readNext(); // Skip header row
            String[] line;

            if (grossIncome < 3250) {
                sssContribution = 135;
            } else if (grossIncome > 24750) {
                sssContribution = 1125;
            } else {
                while ((line = reader.readNext()) != null) {
                    double startRange = Double.parseDouble(line[0].trim());
                    double endRange = Double.parseDouble(line[2].trim());
                    double contribution = Double.parseDouble(line[3].trim());

                    if (startRange <= grossIncome && grossIncome <= endRange) {
                        sssContribution = contribution;
                        break;
                    }
                }
            }
        } catch (IOException | NumberFormatException ex) {
            ex.printStackTrace();
        } finally {
            if (reader != null) {
                try {
                    reader.close();
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
            }
        }
        jTextFieldSssContribution.setText(String.format("%.2f", sssContribution));
        return sssContribution;
    }
    
    
    public double calculatePhilHealth(double grossIncome) {
        double premiumRate = 0.03;
        double monthlyPremium;
        double philHealthContribution;
        
        // Calculate 3% monthly premium rate based on employee's basic salary
        if (grossIncome <= 10000) {
            monthlyPremium = 300;
        } else if (grossIncome >= 60000) {
            monthlyPremium = 1800;
        } else {
            monthlyPremium = grossIncome * premiumRate;
        }
        
        // Monthly premium contribution payments are equally shared between the employee and employer
        philHealthContribution = monthlyPremium * 0.5;
        
        jTextFieldPhilHealthContribution.setText(String.format("%.2f", philHealthContribution));
        return philHealthContribution;
    }

    
    public double calculatePagIbig(double grossIncome) {
        double pagIbigContribution;

        if (grossIncome >= 1000 && grossIncome <= 1500) {
            pagIbigContribution = grossIncome * 0.01;
        } else if (grossIncome > 1500) {
            pagIbigContribution = grossIncome * 0.02;
        } else {
            pagIbigContribution = 0;
        }

        // The maximum Pag-Ibig contribution amount is 100
        if (pagIbigContribution > 100) {
            pagIbigContribution = 100;
        }

        jTextFieldPagIbigContribution.setText(String.format("%.2f", pagIbigContribution));
        return pagIbigContribution;
    }
    
    
    public double calculateTotalContributions(double sssContribution, double philHealthContribution, double pagIbigContribution) {
        double totalContributions = sssContribution + philHealthContribution + pagIbigContribution;
        jTextFieldTotalContributions.setText(String.format("%.2f", totalContributions));
        return totalContributions;
    }
    
    
    public double calculateTaxableIncome(double grossIncome, double totalContributions) {
        double taxableIncome = grossIncome - totalContributions;
        
        // Ensure taxable income is non-negative (contributions are still calculated even if gross income is zero)
        if (taxableIncome < 0) {
            taxableIncome = 0;
        }
        
        jTextFieldTaxableIncome.setText(String.format("%.2f", taxableIncome));
        return taxableIncome;
    }
    
    
    public double calculateWithholdingTax(double taxableIncome) {
        // Withholding tax is calculated after applying deductions
        double withholdingTax;

        if (taxableIncome <= 20832) {
            withholdingTax = 0;
        } else if (taxableIncome < 33333) {
            withholdingTax = (taxableIncome - 20833) * 0.20;
        } else if (taxableIncome < 66667) {
            withholdingTax = 2500 + (taxableIncome - 33333) * 0.25;
        } else if (taxableIncome < 166667) {
            withholdingTax = 10833 + (taxableIncome - 66667) * 0.30;
        } else if (taxableIncome < 666667) {
            withholdingTax = 40833.33 + (taxableIncome - 166667) * 0.32;
        } else {
            withholdingTax = 200833.33 + (taxableIncome - 666667) * 0.35;
        }

        jTextFieldWithholdingTax.setText(String.format("%.2f", withholdingTax));
        return withholdingTax;
    }
    
    
    public double calculateNetIncome(double taxableIncome, double withholdingTax) {
        double netIncome = taxableIncome - withholdingTax;
        jTextFieldNetIncome.setText(String.format("%.2f", netIncome));
        return netIncome;
    }
    
    
    public void calculateTotalDeductions(double totalContributions, double withholdingTax) {
        double totalDeductions = totalContributions + withholdingTax;
        jTextFieldTotalDeductions.setText(String.format("%.2f", totalDeductions));
    } 
    private void jTextFieldEmployeeNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmployeeNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmployeeNoActionPerformed

    private void jTextFieldLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLastNameActionPerformed

    private void jTextFieldFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFirstNameActionPerformed

    private void jTextFieldBirthdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBirthdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBirthdayActionPerformed

    private void jTextFieldPhoneNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPhoneNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhoneNoActionPerformed

    private void jTextFieldStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldStatusActionPerformed

    private void jTextFieldDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDepartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDepartmentActionPerformed

    private void jTextFieldPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPositionActionPerformed

    private void jTextFieldSupervisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSupervisorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSupervisorActionPerformed

    private void jTextFieldSssNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSssNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSssNoActionPerformed

    private void jTextFieldPhilHealthNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPhilHealthNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhilHealthNoActionPerformed

    private void jTextFieldTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTinActionPerformed

    private void jTextFieldPagIbigNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPagIbigNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPagIbigNoActionPerformed

    private void jTextFieldPayslipNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPayslipNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPayslipNoActionPerformed

    private void jTextFieldPayTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPayTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPayTypeActionPerformed

    private void jTextFieldWorkPeriodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldWorkPeriodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldWorkPeriodActionPerformed

    private void jTextFieldTaxableIncome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTaxableIncome2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTaxableIncome2ActionPerformed

    private void jTextFieldWithholdingTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldWithholdingTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldWithholdingTaxActionPerformed

    private void jTextFieldNetIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNetIncomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNetIncomeActionPerformed

    private void jTextFieldBasicSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBasicSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBasicSalaryActionPerformed

    private void jTextFieldDaysWorkedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDaysWorkedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDaysWorkedActionPerformed

    private void jTextFieldHourlyRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHourlyRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHourlyRateActionPerformed

    private void jTextFieldHoursWorkedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHoursWorkedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHoursWorkedActionPerformed

    private void jTextFieldGrossIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGrossIncomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGrossIncomeActionPerformed

    private void jTextFieldRiceSubsidyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRiceSubsidyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRiceSubsidyActionPerformed

    private void jTextFieldPhoneAllowanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPhoneAllowanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhoneAllowanceActionPerformed

    private void jTextFieldClothingAllowanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldClothingAllowanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldClothingAllowanceActionPerformed

    private void jTextFieldTotalBenefitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalBenefitsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalBenefitsActionPerformed

    private void jTextFieldSssContributionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSssContributionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSssContributionActionPerformed

    private void jTextFieldPhilHealthContributionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPhilHealthContributionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhilHealthContributionActionPerformed

    private void jTextFieldPagIbigContributionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPagIbigContributionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPagIbigContributionActionPerformed

    private void jTextFieldTotalContributionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalContributionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalContributionsActionPerformed

    private void jTextFieldGrossIncome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGrossIncome2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGrossIncome2ActionPerformed

    private void jTextFieldTotalContributions2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalContributions2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalContributions2ActionPerformed

    private void jTextFieldTaxableIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTaxableIncomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTaxableIncomeActionPerformed

    private void jTextFieldGrossIncome3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGrossIncome3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGrossIncome3ActionPerformed

    private void jTextFieldTotalBenefits2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalBenefits2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalBenefits2ActionPerformed

    private void jTextFieldTotalDeductionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalDeductionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalDeductionsActionPerformed

    private void jTextFieldTakeHomePayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTakeHomePayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTakeHomePayActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        SalaryPage salaryPage = new SalaryPage(employeeNumber, new PayslipPage(employeeNumber, "01/01/2000", "01/01/2000", 1));
        salaryPage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayslipPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayslipPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayslipPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayslipPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PayslipPage(1, "01/01/2022", "12/31/2022", 1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JLabel jLabelApplyTax;
    private javax.swing.JLabel jLabelBasicSalary;
    private javax.swing.JLabel jLabelBenefits;
    private javax.swing.JLabel jLabelBirthday;
    private javax.swing.JLabel jLabelClothingAllowance;
    private javax.swing.JLabel jLabelContributions;
    private javax.swing.JLabel jLabelDaysWorked;
    private javax.swing.JLabel jLabelDepartment;
    private javax.swing.JLabel jLabelDetails;
    private javax.swing.JLabel jLabelEarnings;
    private javax.swing.JLabel jLabelEmployeeNo;
    private javax.swing.JLabel jLabelFirstName;
    private javax.swing.JLabel jLabelGrossIncome;
    private javax.swing.JLabel jLabelGrossIncome2;
    private javax.swing.JLabel jLabelGrossIncome3;
    private javax.swing.JLabel jLabelHourlyRate;
    private javax.swing.JLabel jLabelHoursWorked;
    private javax.swing.JLabel jLabelLastName;
    private javax.swing.JLabel jLabelNetIncome;
    private javax.swing.JLabel jLabelPagIbigContribution;
    private javax.swing.JLabel jLabelPagIbigNo;
    private javax.swing.JLabel jLabelPayType;
    private javax.swing.JLabel jLabelPayslipNo;
    private javax.swing.JLabel jLabelPhilHealthContribution;
    private javax.swing.JLabel jLabelPhilHealthNo;
    private javax.swing.JLabel jLabelPhoneAllowance;
    private javax.swing.JLabel jLabelPhoneNo;
    private javax.swing.JLabel jLabelPosition;
    private javax.swing.JLabel jLabelRiceSubsidy;
    private javax.swing.JLabel jLabelSssContribution;
    private javax.swing.JLabel jLabelSssNo;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelSummary;
    private javax.swing.JLabel jLabelSupervisor;
    private javax.swing.JLabel jLabelTakeHomePay;
    private javax.swing.JLabel jLabelTaxableIncome;
    private javax.swing.JLabel jLabelTaxableIncome2;
    private javax.swing.JLabel jLabelTin;
    private javax.swing.JLabel jLabelTotalBenefits;
    private javax.swing.JLabel jLabelTotalBenefits2;
    private javax.swing.JLabel jLabelTotalContributions;
    private javax.swing.JLabel jLabelTotalContributions2;
    private javax.swing.JLabel jLabelTotalDeductions;
    private javax.swing.JLabel jLabelTotalTaxableIncome;
    private javax.swing.JLabel jLabelWithholdingTax;
    private javax.swing.JLabel jLabelWorkEndDate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanelApplyTax;
    private javax.swing.JPanel jPanelBenefits;
    private javax.swing.JPanel jPanelBody;
    private javax.swing.JPanel jPanelBottomBorder;
    private javax.swing.JPanel jPanelBottomBorder1;
    private javax.swing.JPanel jPanelBottomBorder2;
    private javax.swing.JPanel jPanelContributions;
    private javax.swing.JPanel jPanelDetails;
    private javax.swing.JPanel jPanelEarnings;
    private javax.swing.JPanel jPanelSummary;
    private javax.swing.JPanel jPanelTaxableIncome;
    private javax.swing.JTextField jTextFieldBasicSalary;
    private javax.swing.JTextField jTextFieldBirthday;
    private javax.swing.JTextField jTextFieldClothingAllowance;
    private javax.swing.JTextField jTextFieldDaysWorked;
    private javax.swing.JTextField jTextFieldDepartment;
    private javax.swing.JTextField jTextFieldEmployeeNo;
    private javax.swing.JTextField jTextFieldFirstName;
    private javax.swing.JTextField jTextFieldGrossIncome;
    private javax.swing.JTextField jTextFieldGrossIncome2;
    private javax.swing.JTextField jTextFieldGrossIncome3;
    private javax.swing.JTextField jTextFieldHourlyRate;
    private javax.swing.JTextField jTextFieldHoursWorked;
    private javax.swing.JTextField jTextFieldLastName;
    private javax.swing.JTextField jTextFieldNetIncome;
    private javax.swing.JTextField jTextFieldPagIbigContribution;
    private javax.swing.JTextField jTextFieldPagIbigNo;
    private javax.swing.JTextField jTextFieldPayType;
    private javax.swing.JTextField jTextFieldPayslipNo;
    private javax.swing.JTextField jTextFieldPhilHealthContribution;
    private javax.swing.JTextField jTextFieldPhilHealthNo;
    private javax.swing.JTextField jTextFieldPhoneAllowance;
    private javax.swing.JTextField jTextFieldPhoneNo;
    private javax.swing.JTextField jTextFieldPosition;
    private javax.swing.JTextField jTextFieldRiceSubsidy;
    private javax.swing.JTextField jTextFieldSssContribution;
    private javax.swing.JTextField jTextFieldSssNo;
    private javax.swing.JTextField jTextFieldStatus;
    private javax.swing.JTextField jTextFieldSupervisor;
    private javax.swing.JTextField jTextFieldTakeHomePay;
    private javax.swing.JTextField jTextFieldTaxableIncome;
    private javax.swing.JTextField jTextFieldTaxableIncome2;
    private javax.swing.JTextField jTextFieldTin;
    private javax.swing.JTextField jTextFieldTotalBenefits;
    private javax.swing.JTextField jTextFieldTotalBenefits2;
    private javax.swing.JTextField jTextFieldTotalContributions;
    private javax.swing.JTextField jTextFieldTotalContributions2;
    private javax.swing.JTextField jTextFieldTotalDeductions;
    private javax.swing.JTextField jTextFieldWithholdingTax;
    private javax.swing.JTextField jTextFieldWorkPeriod;
    // End of variables declaration//GEN-END:variables
}
