package gui.frames;


import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.JOptionPane;


public class SalaryPage extends javax.swing.JFrame {

    private final int employeeNumber;
    private final PayslipPage payslipPage;
    
    /**
     * Creates new form SalaryPage
     */
    
    public SalaryPage(int employeeNumber, PayslipPage payslipPage) {
        this.employeeNumber = employeeNumber;
        this.payslipPage = payslipPage;
        initComponents();
        this.setSize(950, 580);
        addDateRangeListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBody = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jPanelNavBar = new javax.swing.JPanel();
        jButtonBack = new javax.swing.JButton();
        jButtonDetails = new javax.swing.JButton();
        jButtonSalary = new javax.swing.JButton();
        jPanelPayPeriodContainer = new javax.swing.JPanel();
        jComboBoxEndMonth = new javax.swing.JComboBox<>();
        jPanelWorkStartDate = new javax.swing.JPanel();
        jLabelWorkStartDate = new javax.swing.JLabel();
        jPanelMonth = new javax.swing.JPanel();
        jLabelMonth = new javax.swing.JLabel();
        jPanelWorkEndDate = new javax.swing.JPanel();
        jLabelWorkEndDate = new javax.swing.JLabel();
        jPanelMonth1 = new javax.swing.JPanel();
        jLabelMonth1 = new javax.swing.JLabel();
        jComboBoxStartMonth = new javax.swing.JComboBox<>();
        jComboBoxEndYear = new javax.swing.JComboBox<>();
        jComboBoxEndDay = new javax.swing.JComboBox<>();
        jComboBoxStartDay = new javax.swing.JComboBox<>();
        jPanelYear1 = new javax.swing.JPanel();
        jLabelYear1 = new javax.swing.JLabel();
        jComboBoxStartYear = new javax.swing.JComboBox<>();
        jPanelNoOfWorkDaysContainer = new javax.swing.JPanel();
        jPanelSelectWorkDays = new javax.swing.JPanel();
        jLabelSelectWorkDays = new javax.swing.JLabel();
        jComboBoxWorkDays = new javax.swing.JComboBox<>();
        jPanelHeaderSelectPayPeriod1 = new javax.swing.JPanel();
        jLabelSelectPayPeriod1 = new javax.swing.JLabel();
        jButtonComputeSalary = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanelBody.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBody.setMaximumSize(new java.awt.Dimension(950, 580));
        jPanelBody.setMinimumSize(new java.awt.Dimension(950, 580));
        jPanelBody.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(179, 203, 179));
        jPanel4.setLayout(null);

        jButton13.setBackground(new java.awt.Color(254, 254, 225));
        jButton13.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jButton13.setText("Back");
        jButton13.setBorderPainted(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton13);
        jButton13.setBounds(0, 10, 130, 50);

        jPanelBody.add(jPanel4);
        jPanel4.setBounds(0, 0, 0, 550);

        jPanelNavBar.setBackground(new java.awt.Color(0, 51, 102));
        jPanelNavBar.setLayout(null);

        jButtonBack.setBackground(new java.awt.Color(204, 0, 0));
        jButtonBack.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBack.setText("Back");
        jButtonBack.setBorderPainted(false);
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        jPanelNavBar.add(jButtonBack);
        jButtonBack.setBounds(10, 130, 150, 50);

        jButtonDetails.setBackground(new java.awt.Color(255, 255, 204));
        jButtonDetails.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonDetails.setText("Details");
        jButtonDetails.setBorderPainted(false);
        jButtonDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetailsActionPerformed(evt);
            }
        });
        jPanelNavBar.add(jButtonDetails);
        jButtonDetails.setBounds(10, 10, 150, 50);

        jButtonSalary.setBackground(new java.awt.Color(4, 18, 52));
        jButtonSalary.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonSalary.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalary.setText("Salary");
        jButtonSalary.setBorderPainted(false);
        jButtonSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalaryActionPerformed(evt);
            }
        });
        jPanelNavBar.add(jButtonSalary);
        jButtonSalary.setBounds(10, 70, 150, 50);

        jPanelBody.add(jPanelNavBar);
        jPanelNavBar.setBounds(0, 0, 170, 550);

        jPanelPayPeriodContainer.setBackground(new java.awt.Color(0, 51, 102));
        jPanelPayPeriodContainer.setLayout(null);

        jComboBoxEndMonth.setBackground(new java.awt.Color(255, 255, 204));
        jComboBoxEndMonth.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jComboBoxEndMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        jComboBoxEndMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEndMonthActionPerformed(evt);
            }
        });
        jPanelPayPeriodContainer.add(jComboBoxEndMonth);
        jComboBoxEndMonth.setBounds(460, 80, 190, 30);

        jPanelWorkStartDate.setBackground(new java.awt.Color(0, 51, 102));

        jLabelWorkStartDate.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabelWorkStartDate.setForeground(new java.awt.Color(255, 255, 255));
        jLabelWorkStartDate.setText("Work Start Date:");
        jPanelWorkStartDate.add(jLabelWorkStartDate);

        jPanelPayPeriodContainer.add(jPanelWorkStartDate);
        jPanelWorkStartDate.setBounds(200, 20, 190, 30);

        jPanelMonth.setBackground(new java.awt.Color(0, 51, 102));

        jLabelMonth.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabelMonth.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMonth.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelMonth.setText("Month:");
        jPanelMonth.add(jLabelMonth);

        jPanelPayPeriodContainer.add(jPanelMonth);
        jPanelMonth.setBounds(50, 80, 100, 30);

        jPanelWorkEndDate.setBackground(new java.awt.Color(0, 51, 102));

        jLabelWorkEndDate.setBackground(new java.awt.Color(0, 51, 102));
        jLabelWorkEndDate.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabelWorkEndDate.setForeground(new java.awt.Color(255, 255, 255));
        jLabelWorkEndDate.setText("Work End Date:");
        jPanelWorkEndDate.add(jLabelWorkEndDate);

        jPanelPayPeriodContainer.add(jPanelWorkEndDate);
        jPanelWorkEndDate.setBounds(460, 20, 190, 30);

        jPanelMonth1.setBackground(new java.awt.Color(0, 51, 102));

        jLabelMonth1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabelMonth1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMonth1.setText("Day:");
        jPanelMonth1.add(jLabelMonth1);

        jPanelPayPeriodContainer.add(jPanelMonth1);
        jPanelMonth1.setBounds(50, 130, 80, 30);

        jComboBoxStartMonth.setBackground(new java.awt.Color(255, 255, 204));
        jComboBoxStartMonth.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jComboBoxStartMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        jComboBoxStartMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxStartMonthActionPerformed(evt);
            }
        });
        jPanelPayPeriodContainer.add(jComboBoxStartMonth);
        jComboBoxStartMonth.setBounds(200, 80, 190, 30);

        jComboBoxEndYear.setBackground(new java.awt.Color(255, 255, 204));
        jComboBoxEndYear.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jComboBoxEndYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "2024" }));
        jComboBoxEndYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEndYearActionPerformed(evt);
            }
        });
        jPanelPayPeriodContainer.add(jComboBoxEndYear);
        jComboBoxEndYear.setBounds(460, 180, 190, 30);

        jComboBoxEndDay.setBackground(new java.awt.Color(255, 255, 204));
        jComboBoxEndDay.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jComboBoxEndDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboBoxEndDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEndDayActionPerformed(evt);
            }
        });
        jPanelPayPeriodContainer.add(jComboBoxEndDay);
        jComboBoxEndDay.setBounds(460, 130, 190, 30);

        jComboBoxStartDay.setBackground(new java.awt.Color(255, 255, 204));
        jComboBoxStartDay.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jComboBoxStartDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboBoxStartDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxStartDayActionPerformed(evt);
            }
        });
        jPanelPayPeriodContainer.add(jComboBoxStartDay);
        jComboBoxStartDay.setBounds(200, 130, 190, 30);

        jPanelYear1.setBackground(new java.awt.Color(0, 51, 102));

        jLabelYear1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabelYear1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelYear1.setText("Year:");
        jPanelYear1.add(jLabelYear1);

        jPanelPayPeriodContainer.add(jPanelYear1);
        jPanelYear1.setBounds(50, 180, 90, 30);

        jComboBoxStartYear.setBackground(new java.awt.Color(255, 255, 204));
        jComboBoxStartYear.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jComboBoxStartYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "2024" }));
        jComboBoxStartYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxStartYearActionPerformed(evt);
            }
        });
        jPanelPayPeriodContainer.add(jComboBoxStartYear);
        jComboBoxStartYear.setBounds(200, 180, 190, 30);

        jPanelBody.add(jPanelPayPeriodContainer);
        jPanelPayPeriodContainer.setBounds(200, 100, 710, 230);

        jPanelNoOfWorkDaysContainer.setBackground(new java.awt.Color(0, 51, 102));
        jPanelNoOfWorkDaysContainer.setLayout(null);

        jPanelSelectWorkDays.setBackground(new java.awt.Color(0, 51, 102));

        jLabelSelectWorkDays.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabelSelectWorkDays.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSelectWorkDays.setText("Select Number of Work Days :");
        jPanelSelectWorkDays.add(jLabelSelectWorkDays);

        jPanelNoOfWorkDaysContainer.add(jPanelSelectWorkDays);
        jPanelSelectWorkDays.setBounds(40, 20, 290, 31);

        jComboBoxWorkDays.setBackground(new java.awt.Color(255, 255, 204));
        jComboBoxWorkDays.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jComboBoxWorkDays.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21" }));
        jComboBoxWorkDays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxWorkDaysActionPerformed(evt);
            }
        });
        jPanelNoOfWorkDaysContainer.add(jComboBoxWorkDays);
        jComboBoxWorkDays.setBounds(460, 20, 190, 30);

        jPanelBody.add(jPanelNoOfWorkDaysContainer);
        jPanelNoOfWorkDaysContainer.setBounds(200, 370, 710, 70);

        jPanelHeaderSelectPayPeriod1.setBackground(new java.awt.Color(0, 51, 102));
        jPanelHeaderSelectPayPeriod1.setLayout(null);

        jLabelSelectPayPeriod1.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabelSelectPayPeriod1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSelectPayPeriod1.setText("Pay Period");
        jPanelHeaderSelectPayPeriod1.add(jLabelSelectPayPeriod1);
        jLabelSelectPayPeriod1.setBounds(300, 10, 130, 20);

        jPanelBody.add(jPanelHeaderSelectPayPeriod1);
        jPanelHeaderSelectPayPeriod1.setBounds(200, 20, 710, 40);

        jButtonComputeSalary.setBackground(new java.awt.Color(0, 51, 102));
        jButtonComputeSalary.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jButtonComputeSalary.setForeground(new java.awt.Color(255, 255, 255));
        jButtonComputeSalary.setText("Compute Salary");
        jButtonComputeSalary.setBorderPainted(false);
        jButtonComputeSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComputeSalaryActionPerformed(evt);
            }
        });
        jPanelBody.add(jButtonComputeSalary);
        jButtonComputeSalary.setBounds(760, 470, 150, 50);

        getContentPane().add(jPanelBody);
        jPanelBody.setBounds(0, 0, 940, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addDateRangeListener() {
        ItemListener itemListener = new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    updateWorkPeriodTextField();
                    getDaysWorked();
                }
            }
        };

        jComboBoxStartMonth.addItemListener(itemListener);
        jComboBoxEndMonth.addItemListener(itemListener);
        jComboBoxStartDay.addItemListener(itemListener);
        jComboBoxEndDay.addItemListener(itemListener);
        jComboBoxStartYear.addItemListener(itemListener);
        jComboBoxEndYear.addItemListener(itemListener);  
        jComboBoxWorkDays.addItemListener(itemListener);
    }
    
    
    public String[] getWorkPeriod() {
        return updateWorkPeriodTextField();
    }
    
    
    private String[] updateWorkPeriodTextField() {
        int startMonth = jComboBoxStartMonth.getSelectedIndex();
        int endMonth = jComboBoxEndMonth.getSelectedIndex();
        int startDay = jComboBoxStartDay.getSelectedIndex();
        int endDay = jComboBoxEndDay.getSelectedIndex();
        String startYear = (String) jComboBoxStartYear.getSelectedItem();
        String endYear = (String) jComboBoxEndYear.getSelectedItem();
        String startDate = String.format("%02d/%02d/%s", startMonth, startDay, startYear);
        String endDate = String.format("%02d/%02d/%s", endMonth, endDay, endYear);
        return new String[]{startDate, endDate};
    }
    
    
       public int getDaysWorked() {
        int daysWorked = jComboBoxWorkDays.getSelectedIndex();
        return daysWorked;
    }
    
       
    public int getHoursWorked(int daysWorked) {
        int hoursWorked = daysWorked * 8;
        return hoursWorked;
    }
    
    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        DetailsPage detailsPage = new DetailsPage(employeeNumber);
        detailsPage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetailsActionPerformed
        // TODO add your handling code here:
        DetailsPage detailsPage = new DetailsPage(employeeNumber);
        detailsPage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonDetailsActionPerformed

    private void jButtonSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalaryActionPerformed

    private void jComboBoxEndMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEndMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEndMonthActionPerformed

    private void jButtonComputeSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComputeSalaryActionPerformed
        // Validate combo box selections
        int startMonth = jComboBoxStartMonth.getSelectedIndex();
        int endMonth = jComboBoxEndMonth.getSelectedIndex();
        int startDay = jComboBoxStartDay.getSelectedIndex();
        int endDay = jComboBoxEndDay.getSelectedIndex();
        int startYear = jComboBoxStartYear.getSelectedIndex();
        int endYear = jComboBoxEndYear.getSelectedIndex();
        int workDays = jComboBoxWorkDays.getSelectedIndex();

        // Check if any combo box is not selected
        if (startMonth == 0 || endMonth == 0 || startDay == 0 || endDay == 0 || startYear == 0 || endYear == 0 || workDays == 0) {
            JOptionPane.showMessageDialog(this, "Please select valid options for all fields before proceeding.", "Invalid Selection", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Check if month selections are for 1-month cutoff period
        if (!(startMonth == endMonth || startMonth == endMonth - 1)) {
            JOptionPane.showMessageDialog(this, "Please select valid months as this program only computes for monthly payslips.", "Invalid Selection", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Calculate the total number of days in the cutoff period
        int totalDays;
        if (startMonth == endMonth) {
            totalDays = endDay - startDay + 1;
        } else {
            totalDays = (31 - startDay + 1) + endDay;
        }
        
        // Validate that total days in the cutoff period do not exceed 31 days
        if (totalDays > 31) {
            JOptionPane.showMessageDialog(this, "Invalid date range. The start and end dates should not span more than one month.", "Invalid Selection", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validate that workdays do not exceed total days in the cutoff period
        if (workDays > totalDays) {
            JOptionPane.showMessageDialog(this, "Invalid number of workdays. Please ensure that the number of workdays does not \nexceed the total days in the cutoff period based on the inputted start and end dates.", "Invalid Selection", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String[] workPeriod = getWorkPeriod();
        int daysWorked = getDaysWorked();
        PayslipPage payslipPage = new PayslipPage(employeeNumber, workPeriod[0], workPeriod[1], daysWorked);
        payslipPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonComputeSalaryActionPerformed

    private void jComboBoxStartMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxStartMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxStartMonthActionPerformed

    private void jComboBoxEndYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEndYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEndYearActionPerformed

    private void jComboBoxEndDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEndDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEndDayActionPerformed

    private void jComboBoxStartDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxStartDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxStartDayActionPerformed

    private void jComboBoxWorkDaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxWorkDaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxWorkDaysActionPerformed

    private void jComboBoxStartYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxStartYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxStartYearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalaryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalaryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalaryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalaryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalaryPage(12345, new PayslipPage(1, "01/01/2022", "12/31/2022", 1)).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonComputeSalary;
    private javax.swing.JButton jButtonDetails;
    private javax.swing.JButton jButtonSalary;
    private javax.swing.JComboBox<String> jComboBoxEndDay;
    private javax.swing.JComboBox<String> jComboBoxEndMonth;
    private javax.swing.JComboBox<String> jComboBoxEndYear;
    private javax.swing.JComboBox<String> jComboBoxStartDay;
    private javax.swing.JComboBox<String> jComboBoxStartMonth;
    private javax.swing.JComboBox<String> jComboBoxStartYear;
    private javax.swing.JComboBox<String> jComboBoxWorkDays;
    private javax.swing.JLabel jLabelMonth;
    private javax.swing.JLabel jLabelMonth1;
    private javax.swing.JLabel jLabelSelectPayPeriod1;
    private javax.swing.JLabel jLabelSelectWorkDays;
    private javax.swing.JLabel jLabelWorkEndDate;
    private javax.swing.JLabel jLabelWorkStartDate;
    private javax.swing.JLabel jLabelYear1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelBody;
    private javax.swing.JPanel jPanelHeaderSelectPayPeriod1;
    private javax.swing.JPanel jPanelMonth;
    private javax.swing.JPanel jPanelMonth1;
    private javax.swing.JPanel jPanelNavBar;
    private javax.swing.JPanel jPanelNoOfWorkDaysContainer;
    private javax.swing.JPanel jPanelPayPeriodContainer;
    private javax.swing.JPanel jPanelSelectWorkDays;
    private javax.swing.JPanel jPanelWorkEndDate;
    private javax.swing.JPanel jPanelWorkStartDate;
    private javax.swing.JPanel jPanelYear1;
    // End of variables declaration//GEN-END:variables
}
